// lib/buildTool/webpack/sampleApp/templates/ng2/TypeScript/demoModule/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';

// Require the CSS file explicitly (or it could be defined as an entry-point too).
<%
var cssEntryPointFiles = resources.sampleApp.cssSourceFormat[buildCSS.sourceFormat].entryPointFileNames.map(function(file) {
  return paths.input.stylesDir + file;
});

cssEntryPointFiles.forEach(function(file) { -%>
require('./<%= file %>');
<% }); -%>

/*
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [],
  template: `
    <main>
      <router-outlet></router-outlet>
    </main>
  `
})
export class AppComponent { }

// lib/buildTool/webpack/sampleApp/templates/react/demoModule/app.jsx
'use strict';

import React from 'react';
import {render} from 'react-dom';
import {AppContainer} from 'react-hot-loader';
import AppComponent from './AppComponent';

// Require the CSS file explicitly (or it could be defined as an entry-point too).
<%
var cssEntryPointFiles = resources.sampleApp.cssSourceFormat[buildCSS.sourceFormat].entryPointFileNames.map(function(file) {
  return paths.input.stylesDir + file;
});

cssEntryPointFiles.forEach(function(file) { -%>
require('./<%= file %>');
<% }); -%>


render(
  <AppContainer>
    <AppComponent/>
  </AppContainer>,
  document.getElementById('content')
);

// Hot Module Replacement API.
if (module.hot) {
  module.hot.accept('./AppComponent', render);
}
